// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `head.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let modes = _ModuleRegistry.module("modes");

    const iceC_modes_actions_ids = [
        "::Ice::Object",
        "::modes::actions"
    ];

    modes.actions = class extends Ice.Object
    {
    };

    modes.actionsPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(modes.actions, modes.actionsPrx, iceC_modes_actions_ids, 1,
    {
        "printString": [, , , , , [[7]], , , , ],
        "printStringWithRet": [, , , , [3], [[7]], , , , ],
        "getnum": [, , , , [1], [[3], [3]], [[3]], , , ],
        "compute": [, , , , [3], [[3], [3]], , , , ]
    });
    exports.modes = modes;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require : this.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports : this));
